const products = [
  {
    id: "1",
    name: "Fresh Organic Apples",
    image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6bcd6?w=500&auto=format&fit=crop&q=60",
    description: "Picked fresh from organic orchards, these apples are crisp, sweet, and packed with vitamins. Perfect for snacking or baking delicious pies.",
    brand: "Nature's Gift",
    category: "Fruits",
    price: 120.00,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
    isSale: true,
    salePrice: 99.00,
  },
  {
    id: "2",
    name: "Crisp Iceberg Lettuce",
    image: "https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=500&auto=format&fit=crop&q=60",
    description: "Hydrating and crunchy Iceberg lettuce. The perfect base for your salads or a crunchy topping for burgers and sandwiches.",
    brand: "GreenLeaf Farms",
    category: "Vegetables",
    price: 60.00,
    countInStock: 0, // Testing Out of Stock
    rating: 4.0,
    numReviews: 8,
    isSale: false,
  },
  {
    id: "3",
    name: "Whole Wheat Bread",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=60",
    description: "Freshly baked daily using 100% whole grain flour. High in fiber and perfect for healthy sandwiches or morning toast.",
    brand: "Bakery Fresh",
    category: "Bakery",
    price: 80.00,
    countInStock: 5,
    rating: 4.8,
    numReviews: 25,
    isSale: true,
    salePrice: 65.00,
  },
  {
    id: "4",
    name: "Organic Baby Spinach",
    image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500&auto=format&fit=crop&q=60",
    description: "Tender, pre-washed baby spinach leaves. Great for smoothies, sautéing with garlic, or fresh summer salads.",
    brand: "Pure Greens",
    category: "Vegetables",
    price: 150.00,
    countInStock: 15,
    rating: 4.2,
    numReviews: 15,
    isSale: false,
  },
  {
    id: "5",
    name: "Fresh Strawberries",
    image: "https://images.unsplash.com/photo-1464965911861-746a04b05ca6?w=500&auto=format&fit=crop&q=60",
    description: "Sweet, juicy, and bright red strawberries. Excellent for desserts, breakfast bowls, or dipping in chocolate.",
    brand: "Berry Patch",
    category: "Fruits",
    price: 200.00,
    countInStock: 7,
    rating: 4.7,
    numReviews: 30,
    isSale: true,
    salePrice: 175.00,
  },
  {
    id: "6",
    name: "Fresh Local Tomatoes",
    image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&auto=format&fit=crop&q=60",
    description: "Ripened on the vine for maximum flavor. These local tomatoes are juicy and perfect for sauces, salads, or slicing.",
    brand: "Farm Direct",
    category: "Vegetables",
    price: 40.00,
    countInStock: 20,
    rating: 3.8,
    numReviews: 10,
    isSale: false,
  }
];

export default products;